config/routes.rb
GistLite::Application.routes.draw do
  resources :gists
  resources :comments

  devise_for :users

  root 'gists#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :user, :gist, presence: true

  belongs_to :gist
  belongs_to :user
end

app/models/gist.rb
class Gist < ActiveRecord::Base
  validates :file_name, :text, :user, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def after_sign_in_path_for(resource)
    gists_path
  end
  
#  def after_sign_out_path_for(resource)
#    gists_path
#  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, only: [:create]
  
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    
    unless @comment.save
      flash[:error] = "Don`t save comment: " + @comment.errors.full_messages.join(', ')
    end 
    redirect_to gist_path(@comment.gist)
  end  
  
  
  private
  
  def comment_params
    params.require(:comment).permit(:text, :gist_id)
  end

end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_gist, only: [:show, :edit, :update, :destroy]
  before_action :user_valid, only: [:update, :destroy]
  
  respond_to :html

  def index    
    if params[:gists] == "my" && current_user
      @gists = Gist.where(user: current_user)
    else      
      @gists = Gist.all
    end
  end

  def show
    @comment_new = Comment.new(gist: @gist) if current_user 
    #, user: current_user - пользователь не инициализируется так как при записи 
    #испольуется текущий пользователь
  end

  def new
    @gist = Gist.new
  end

  def edit
  end

  def create
    @gist = Gist.new(gist_params)
    @gist.user = current_user
    
    if @gist.save
      redirect_to gist_path(@gist)
    else
      render "new"
    end
  end

  def update    
    if @gist.update(gist_params)
      redirect_to gist_path(@gist)
    else
      render "edit"
    end
  end

  def destroy
    @gist.destroy
    redirect_to gists_path
  end

  private
    
  def set_gist
    @gist = Gist.includes(:user, comments: :user).find(params[:id])
  end

  def gist_params
    params.require(:gist).permit(:file_name, :text)
  end
  
  def user_valid
    if current_user != @gist.user
      flash[:error] = "Access denied"
      redirect_to gist_path(@gist)
      return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gists_helper.rb
module GistsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
    <div id="editor_comment" class="editor_comment"></div>
    <%= f.hidden_field :text %>
    <%= f.hidden_field :gist_id %>
    <div align="left">
      <%= f.submit %>
    </div>
<% end %>

app/views/comments/_show.html.erb
<div align="right"><%=comment.user.email%></div>
<input type="hidden" value="<%= comment.text %>" id="text_editor_comment_<%= comment.id %>"/>
<div id="editor_comment_<%= comment.id %>"></div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

app/views/gists/_form.html.erb
<%= form_for(@gist) do |f| %>
  <% if @gist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gist.errors.count, "error") %> prohibited this gist from being saved:</h2>
      <ul>
      <% @gist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="div_container">
    <div align="left">
      <%= f.text_field :file_name %>
    </div>
    <div id="editor" class="editor__form"></div>
    <%= f.hidden_field :text %>
    <div align="left">
      <%= f.submit %>
    </div>
  </div>

<% end %>

app/views/gists/edit.html.erb
<h1>Editing gist</h1>
<%= render 'form' %>

app/views/gists/index.html.erb
<h1>Listing gists</h1>
<%= link_to 'New Gist', new_gist_path %>

<div class="div_container">
  <% @gists.each do |gist| %>
    <div class="div_h_container">
      <div class="div_h_left">
        <%= gist.file_name %>
      </div>
      <div class="div_h_right">
        <%= gist.user.email %>
      </div>
    </div>
    <input type="hidden" value="<%= gist.text %>" id="text_editor_<%= gist.id %>"/>
    <div id="editor_<%= gist.id %>" class="editor_index"></div>
    <div class="div_h_container">
      <div class="div_h_left">
        Insert comments count here
      </div>
      <div class="div_h_right">
        <%= link_to 'Show', gist %>
      </div>
    </div>
  <% end %>
</div>

app/views/gists/new.html.erb
<h1>New gist</h1>

<%= render 'form' %>

app/views/gists/show.html.erb
<h1>View gist</h1>
<div class="div_container">
  <div class="div_h_container">
    <div class="div_h_left">
      <%= @gist.file_name %>
    </div>
    <div class="div_h_right">
      <%= @gist.user.email %>
    </div>
  </div>
  <input type="hidden" value="<%= @gist.text %>" id="text_editor"/>
  <div id="editor" class="editor_show"></div>
  <div class="div_h_container">
    <div class="div_h_right">
      <% if current_user && current_user == @gist.user %>
        <%= link_to 'Edit', edit_gist_path(@gist) %>
        <%= link_to 'Destroy', @gist, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  <div>
    <ul class="list-group" id="comments_gist_<%= @gist.id %>">
      <li class="list-group-item">
        <div align="center">Comments</div>
      </li>
      <% @gist.comments.each do |c| %>
        <li class="list-group-item" id="comment_<%= c.id %>"> 
          <%= render 'comments/show', comment: c %>
        </li>
      <% end %>
      <li class="list-group-item">
        <%if @comment_new %>
          <%= render 'comments/form', comment: @comment_new %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GistLite</title>
   
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <script src="https://ace.c9.io/build/src/ace.js" type="text/javascript" charset="utf-8"></script>
  </head>
  <body>
  
  
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <%= link_to "All gists", gists_path(gists: :all), class: "btn btn-info" + (params[:gists] != "my" ? " active" : "") %>
        <%= link_to "My gists", gists_path(gists: :my), class: "btn btn-info" + (params[:gists] == "my" ? " active" : "") %>
  
  <!--
        <li class="nav-item">
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
   
       </li>
  -->
      </ul>
      
      <% if user_signed_in? %>
      <%=current_user.email%>
      <%= link_to "Log Out", destroy_user_session_path, method: :get, class: "btn btn-info"%>
      <%else%>
      <%= link_to "Log In", new_user_session_path, method: :get, class: "btn btn-info"%>
      <%end%>
  
    </nav>
    
    <div class="error"><%=flash[:error]%></div>
    
    <div align="center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>